on:
    pull_request:
        branches: ["main"]
        paths:
            - "terraform/**"

jobs:
    TerraformFormatCheck:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v2.0.2

            - name: Check formatting
              run: | 
                pwd
                cd terraform
                pwd
                terraform fmt --recursive
                if [[ $(terraform fmt --recursive) ]]; then
                    echo "::error::The terraform configuration is not formatted correctly. Run the following locally and commit the changes before proceeding:"
                    echo "terraform fmt --recursive"
                    exit 1
                else
                    echo "Nothing to format, you can proceed."
                fi